import Head from "next/head";

export default function New() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Javohir</h1>
        <p>27.03.2025</p>
      </div>
    </>
  );
}
